"""email added to user table

Revision ID: 314614c13fa7
Revises: ebf4d14086c4
Create Date: 2025-02-15 16:00:27.307684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314614c13fa7'
down_revision = 'ebf4d14086c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
